# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import batalla_pb2 as batalla__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in batalla_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MotorMultijugadorStub(object):
    """--- DEFINICIÓN DEL SERVICIO ---
    (Aquí están tus funciones, adaptadas para usar los mensajes de arriba)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarJugador = channel.unary_unary(
                '/batalla.MotorMultijugador/RegistrarJugador',
                request_serializer=batalla__pb2.PeticionRegistro.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaRegistro.FromString,
                _registered_method=True)
        self.ObtenerCantidadConectados = channel.unary_unary(
                '/batalla.MotorMultijugador/ObtenerCantidadConectados',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaEntero.FromString,
                _registered_method=True)
        self.ObtenerMaxJugadores = channel.unary_unary(
                '/batalla.MotorMultijugador/ObtenerMaxJugadores',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaEntero.FromString,
                _registered_method=True)
        self.ColocarBarco = channel.unary_unary(
                '/batalla.MotorMultijugador/ColocarBarco',
                request_serializer=batalla__pb2.PeticionCoordenada.SerializeToString,
                response_deserializer=batalla__pb2.Vacio.FromString,
                _registered_method=True)
        self.DeclararListo = channel.unary_unary(
                '/batalla.MotorMultijugador/DeclararListo',
                request_serializer=batalla__pb2.PeticionJugador.SerializeToString,
                response_deserializer=batalla__pb2.Vacio.FromString,
                _registered_method=True)
        self.TodosListos = channel.unary_unary(
                '/batalla.MotorMultijugador/TodosListos',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaBooleano.FromString,
                _registered_method=True)
        self.DeQuienEsElTurno = channel.unary_unary(
                '/batalla.MotorMultijugador/DeQuienEsElTurno',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaEntero.FromString,
                _registered_method=True)
        self.Disparar = channel.unary_unary(
                '/batalla.MotorMultijugador/Disparar',
                request_serializer=batalla__pb2.PeticionCoordenada.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaEntero.FromString,
                _registered_method=True)
        self.ObtenerEstadoTablero = channel.unary_unary(
                '/batalla.MotorMultijugador/ObtenerEstadoTablero',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaTablero.FromString,
                _registered_method=True)
        self.ObtenerGanador = channel.unary_unary(
                '/batalla.MotorMultijugador/ObtenerGanador',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaEntero.FromString,
                _registered_method=True)
        self.ObtenerMarcador = channel.unary_unary(
                '/batalla.MotorMultijugador/ObtenerMarcador',
                request_serializer=batalla__pb2.Vacio.SerializeToString,
                response_deserializer=batalla__pb2.RespuestaMarcador.FromString,
                _registered_method=True)


class MotorMultijugadorServicer(object):
    """--- DEFINICIÓN DEL SERVICIO ---
    (Aquí están tus funciones, adaptadas para usar los mensajes de arriba)
    """

    def RegistrarJugador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCantidadConectados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerMaxJugadores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ColocarBarco(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclararListo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TodosListos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeQuienEsElTurno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disparar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerEstadoTablero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerGanador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerMarcador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotorMultijugadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarJugador': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarJugador,
                    request_deserializer=batalla__pb2.PeticionRegistro.FromString,
                    response_serializer=batalla__pb2.RespuestaRegistro.SerializeToString,
            ),
            'ObtenerCantidadConectados': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCantidadConectados,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaEntero.SerializeToString,
            ),
            'ObtenerMaxJugadores': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerMaxJugadores,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaEntero.SerializeToString,
            ),
            'ColocarBarco': grpc.unary_unary_rpc_method_handler(
                    servicer.ColocarBarco,
                    request_deserializer=batalla__pb2.PeticionCoordenada.FromString,
                    response_serializer=batalla__pb2.Vacio.SerializeToString,
            ),
            'DeclararListo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclararListo,
                    request_deserializer=batalla__pb2.PeticionJugador.FromString,
                    response_serializer=batalla__pb2.Vacio.SerializeToString,
            ),
            'TodosListos': grpc.unary_unary_rpc_method_handler(
                    servicer.TodosListos,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaBooleano.SerializeToString,
            ),
            'DeQuienEsElTurno': grpc.unary_unary_rpc_method_handler(
                    servicer.DeQuienEsElTurno,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaEntero.SerializeToString,
            ),
            'Disparar': grpc.unary_unary_rpc_method_handler(
                    servicer.Disparar,
                    request_deserializer=batalla__pb2.PeticionCoordenada.FromString,
                    response_serializer=batalla__pb2.RespuestaEntero.SerializeToString,
            ),
            'ObtenerEstadoTablero': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstadoTablero,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaTablero.SerializeToString,
            ),
            'ObtenerGanador': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerGanador,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaEntero.SerializeToString,
            ),
            'ObtenerMarcador': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerMarcador,
                    request_deserializer=batalla__pb2.Vacio.FromString,
                    response_serializer=batalla__pb2.RespuestaMarcador.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'batalla.MotorMultijugador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('batalla.MotorMultijugador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotorMultijugador(object):
    """--- DEFINICIÓN DEL SERVICIO ---
    (Aquí están tus funciones, adaptadas para usar los mensajes de arriba)
    """

    @staticmethod
    def RegistrarJugador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/RegistrarJugador',
            batalla__pb2.PeticionRegistro.SerializeToString,
            batalla__pb2.RespuestaRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCantidadConectados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/ObtenerCantidadConectados',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaEntero.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerMaxJugadores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/ObtenerMaxJugadores',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaEntero.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ColocarBarco(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/ColocarBarco',
            batalla__pb2.PeticionCoordenada.SerializeToString,
            batalla__pb2.Vacio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclararListo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/DeclararListo',
            batalla__pb2.PeticionJugador.SerializeToString,
            batalla__pb2.Vacio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TodosListos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/TodosListos',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaBooleano.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeQuienEsElTurno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/DeQuienEsElTurno',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaEntero.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disparar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/Disparar',
            batalla__pb2.PeticionCoordenada.SerializeToString,
            batalla__pb2.RespuestaEntero.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerEstadoTablero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/ObtenerEstadoTablero',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaTablero.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerGanador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/ObtenerGanador',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaEntero.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerMarcador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batalla.MotorMultijugador/ObtenerMarcador',
            batalla__pb2.Vacio.SerializeToString,
            batalla__pb2.RespuestaMarcador.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
