# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: batalla.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'batalla.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbatalla.proto\x12\x07\x62\x61talla\"\x07\n\x05Vacio\" \n\x0fRespuestaEntero\x12\r\n\x05valor\x18\x01 \x01(\x05\"\"\n\x11RespuestaBooleano\x12\r\n\x05valor\x18\x01 \x01(\x08\"\"\n\x11RespuestaMarcador\x12\r\n\x05texto\x18\x01 \x01(\t\"+\n\x10PeticionRegistro\x12\x17\n\x0ftotal_esperados\x18\x01 \x01(\x05\"\'\n\x11RespuestaRegistro\x12\x12\n\nid_jugador\x18\x01 \x01(\x05\"%\n\x0fPeticionJugador\x12\x12\n\nid_jugador\x18\x01 \x01(\x05\">\n\x12PeticionCoordenada\x12\x12\n\nid_jugador\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"\x17\n\x04\x46ila\x12\x0f\n\x07valores\x18\x01 \x03(\x05\"0\n\x10RespuestaTablero\x12\x1c\n\x05\x66ilas\x18\x01 \x03(\x0b\x32\r.batalla.Fila2\xd8\x05\n\x11MotorMultijugador\x12I\n\x10RegistrarJugador\x12\x19.batalla.PeticionRegistro\x1a\x1a.batalla.RespuestaRegistro\x12\x45\n\x19ObtenerCantidadConectados\x12\x0e.batalla.Vacio\x1a\x18.batalla.RespuestaEntero\x12?\n\x13ObtenerMaxJugadores\x12\x0e.batalla.Vacio\x1a\x18.batalla.RespuestaEntero\x12;\n\x0c\x43olocarBarco\x12\x1b.batalla.PeticionCoordenada\x1a\x0e.batalla.Vacio\x12\x39\n\rDeclararListo\x12\x18.batalla.PeticionJugador\x1a\x0e.batalla.Vacio\x12\x39\n\x0bTodosListos\x12\x0e.batalla.Vacio\x1a\x1a.batalla.RespuestaBooleano\x12<\n\x10\x44\x65QuienEsElTurno\x12\x0e.batalla.Vacio\x1a\x18.batalla.RespuestaEntero\x12\x41\n\x08\x44isparar\x12\x1b.batalla.PeticionCoordenada\x1a\x18.batalla.RespuestaEntero\x12\x41\n\x14ObtenerEstadoTablero\x12\x0e.batalla.Vacio\x1a\x19.batalla.RespuestaTablero\x12:\n\x0eObtenerGanador\x12\x0e.batalla.Vacio\x1a\x18.batalla.RespuestaEntero\x12=\n\x0fObtenerMarcador\x12\x0e.batalla.Vacio\x1a\x1a.batalla.RespuestaMarcadorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'batalla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VACIO']._serialized_start=26
  _globals['_VACIO']._serialized_end=33
  _globals['_RESPUESTAENTERO']._serialized_start=35
  _globals['_RESPUESTAENTERO']._serialized_end=67
  _globals['_RESPUESTABOOLEANO']._serialized_start=69
  _globals['_RESPUESTABOOLEANO']._serialized_end=103
  _globals['_RESPUESTAMARCADOR']._serialized_start=105
  _globals['_RESPUESTAMARCADOR']._serialized_end=139
  _globals['_PETICIONREGISTRO']._serialized_start=141
  _globals['_PETICIONREGISTRO']._serialized_end=184
  _globals['_RESPUESTAREGISTRO']._serialized_start=186
  _globals['_RESPUESTAREGISTRO']._serialized_end=225
  _globals['_PETICIONJUGADOR']._serialized_start=227
  _globals['_PETICIONJUGADOR']._serialized_end=264
  _globals['_PETICIONCOORDENADA']._serialized_start=266
  _globals['_PETICIONCOORDENADA']._serialized_end=328
  _globals['_FILA']._serialized_start=330
  _globals['_FILA']._serialized_end=353
  _globals['_RESPUESTATABLERO']._serialized_start=355
  _globals['_RESPUESTATABLERO']._serialized_end=403
  _globals['_MOTORMULTIJUGADOR']._serialized_start=406
  _globals['_MOTORMULTIJUGADOR']._serialized_end=1134
# @@protoc_insertion_point(module_scope)
